[package]
name = "tonjson"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[build-dependencies]
cmake = "0.1.48"

[dependencies]
tonlibjson-rs = { git = "https://github.com/akostylev0/tonlibjson-rs.git" }
anyhow = "1.0.57"
serde = { version = "1.0.136", features = ["serde_derive"] }
serde_json = "1.0.79"
tokio = { version = "1.18.2", features = ["rt-multi-thread", "sync", "macros", "time"] }
uuid = { version = "1.0.0", features = ["v4", "fast-rng"] }
futures = "0.3.21"
async-stream = "0.3.3"
