name: rust-clippy analyze

on:
  pull_request:
    branches: [ "master" ]

jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: arduino/setup-protoc@v2

      - name: Restore llvm repos
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15

      - name: Install libc++-15
        run: sudo apt-get install -y libc++-15-dev libc++abi-15-dev libsecp256k1-dev libsodium-dev

      - name: Switch clang version to 15
        run: |
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 101
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 101

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --target x86_64-unknown-linux-gnu
