name: rust-clippy analyze

on:
  pull_request:
    branches: [ "master" ]

jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on:
      group: "CPUBound"
    permissions:
      contents: read
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: arduino/setup-protoc@v2

      - name: Restore llvm repos
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16

      - name: Install libc++-16
        run: sudo apt-get install -y libc++-16-dev libc++abi-16-dev libsecp256k1-dev libsodium-dev

      - name: Switch clang version to 16
        run: |
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 101
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 101

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --target x86_64-unknown-linux-gnu
        env:
          SCCACHE_GHA_ENABLED: "true"

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats