name: tvm-grpc release
on:
  workflow_dispatch:
#  push:
#    tags:
#      - 'tvm-grpc-v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-bin:
    strategy:
      matrix:
        include:
          - features: ''
          - features: 'testnet'
    runs-on:
      group: "CPUBound"
    steps:
      - uses: ./.github/actions/prepare/action.yml
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build mainnet version
        run: cargo build -v --bin tvm-grpc --target x86_64-unknown-linux-gnu --release --features "${{ matrix.features }}"
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CMAKE_C_COMPILER_LAUNCHER: "sccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
      - run: ldd ./target/x86_64-unknown-linux-gnu/release/tvm-grpc
