name: tvm-grpc release
on:
  workflow_dispatch:
#  push:
#    tags:
#      - 'tvm-grpc-v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-bin:
    runs-on:
      group: "CPUBound"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: arduino/setup-protoc@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 16
      - run: cargo build -v --bin tvm-grpc --target x86_64-unknown-linux-gnu